const foods = [
    {
      title:'Dr pie',
      subtitle:'Anesthesiology',
      description:'Doctors, also known as physicians, are licensed health professionals who maintain and restore human health through the practice of medicine. They examine patients, review their medical history, diagnose illnesses or injuries, administer treatment, and counsel patients on their health and well being.',
      time:4.2,
      img:'https://img.freepik.com/free-photo/pleased-young-female-doctor-wearing-medical-robe-stethoscope-around-neck-standing-with-closed-posture_409827-254.jpg?size=626&ext=jpg',
      visit:500,
      id:100123
    },
    {
      title:'Dr Arina',
      subtitle:'Dermatologists',
      description:'',
      time:5.5,
      img:'https://cdn.buttercms.com/lAPMaVZ8QM6flKo1StMK',

      visit:450,
      id:1001234,
    },
    {
      title:'Dr Alisan',
      subtitle:'Ophthalmologists',
      description:'Doctors, also known as physicians, are licensed health professionals who maintain and restore human health through the practice of medicine. They examine patients, review their medical history, diagnose illnesses or injuries, administer treatment, and counsel patients on their health and well being.',
      time:2.3,
      img:'https://us.123rf.com/450wm/rido/rido1704/rido170400095/76465313-portrait-of-smiling-doctor-with-stethoscope-around-his-neck-at-medical-clinic-happy-smiling-senior-d.jpg?ver=6',

      visit:600,
      id:100145234,
    },
    {
      title:'Dr Palot',
      subtitle:'Colon Hydrotherpist',
      description:'Physicians should be personable, great listeners, and empathetic to the concerns of their patients,” he elaborates. “They should not be condescending or arrogant. They should treat others as they want to be treated.” "Physicians should be personable, great listeners, and empathetic to the concerns of their patients.',
      time:1.3,
      img:'https://media.istockphoto.com/photos/portrait-of-mature-male-doctor-wearing-white-coat-standing-in-picture-id1203995945?k=20&m=1203995945&s=612x612&w=0&h=g0_ioNezBqP0NXrR_36-A5NDHIR0nLabFFrAQVk4PhA=',
      visit:600,
      id:46599882,
    },
    {
      title:'Dr Albert',
      subtitle:'Geriatric medicine doctors',
      description:'Candidates need to complete a residency program or fellowship in a hospital before they can become licensed Doctors. Depending on the specialization, this will last anywhere from three to seven years. All applicants are required to have some experience before they can practice medicine in a primary care capacity.',
      time:10.40,
      img:'https://st3.depositphotos.com/10654668/i/600/depositphotos_138445604-stock-photo-male-doctor-in-hospital.jpg',
      visit:600,
      id:46599882,
    },
    {
      title:'Dr Abdul',
      subtitle:'Dermatologists',
      description:'Doctors need a bachelor’s degree, a medical degree and three to seven years in residency or a fellowship, depending on the specialization. While no specific major is required for the bachelor’s degree, most students usually choose a science such as biology or chemistry. In order to be accepted into a medical school, students must have completed their bachelor’s degrees and taken the MAT (Medical College Admission Test). Most medical school programs last four years.',
      time:9.20,
      img:'https://ak.picdn.net/shutterstock/videos/6645089/thumb/1.jpg',
      visit:850,
      id:34997385,
    },
    {
      title:'Dr Maria',
      subtitle:'Ophthalmologists',
      description:'Candidates need to complete a residency program or fellowship in a hospital before they can become licensed Doctors. Depending on the specialization, this will last anywhere from three to seven years. All applicants are required to have some experience before they can practice medicine in a primary care capacity.',
      time:8.3,
      img:'',
      visit:1000,
      id:93834376,
    },
    {
      title:'Dr Mizan',
      subtitle:'Obstetrician/gynecologists',
      description:'Doctors need a bachelor’s degree, a medical degree and three to seven years in residency or a fellowship, depending on the specialization. While no specific major is required for the bachelor’s degree, most students usually choose a science such as biology or chemistry. In order to be accepted into a medical school, students must have completed their bachelor’s degrees and taken the MCAT (Medical College Admission Test). Most medical school programs last four years.',
      time:4.3,
      img:'https://thevoiceofblackcincinnati.com/wp-content/uploads/2021/06/AdobeStock_305412791-scaled.jpeg',
      visit:650,
      id:84425836,
    },
    {
      title:'Dr Munirul',
      subtitle:'Cardiologists',
      description:'Doctors, also known as physicians, are licensed health professionals who maintain and restore human health through the practice of medicine. They examine patients, review their medical history, diagnose illnesses or injuries, administer treatment, and counsel patients on their health and well being.',
      time:3,
      img:'https://post.psychcentral.com/wp-content/uploads/2020/09/Black_Male_Doctor_Portrait_732x549-thumbnail.jpg',
      visit:900,
      id:44344974,
    },
    {
      title:'Dr Alisa',
      subtitle:'Endocrinologists',
      description:'Candidates need to complete a residency program or fellowship in a hospital before they can become licensed Doctors. Depending on the specialization, this will last anywhere from three to seven years. All applicants are required to have some experience before they can practice medicine in a primary care capacity.',
      time:8,
      img:'https://womeninwhitecoats.com/wp-content/uploads/2020/02/IMG_0414-1080x675.jpg',
      visit:800,
      id:87858922,
    },

  ]